### ISSUE TITLE
3D volumes

### ISSUE THREAD

**Issue by Olivier222** [dovahcrow/patchify.py#2]
Can this be used for 3D volumes? Or is it limited to 2D images?

**Comment by dovahcrow** [comment]
No, volumes are not support while I believe the source code can be adapt to any higher dimension.

**Comment by vdivakar** [comment]
For 3D input volume, you can create patches as follows:
```python
patches = patchify(image, (2,2,3), step=1) # patch shape [2,2,3]
```

For merging 3D patches, I've extended the source code & created a pull request.

**Comment by dovahcrow** [comment]
@Oliver222 Hi I merged the great patch from @vdivakar. Could you please have a try on that?

**Comment by dovahcrow** [comment]
I think it is fixed. Issue closed.
