### ISSUE TITLE
3D unpatchify issue 

### ISSUE THREAD

**Issue by Jonlenes** [dovahcrow/patchify.py#4]
Not working when I tried with real (and "big" image).
[Colab here](https://colab.research.google.com/drive/1DL5cQ7lo9rD7cBRH7_S3lSaytaiYPQMa?usp=sharing)
Thanks.

**Comment by dovahcrow** [comment]
Fixed! Try it in the same Colab.

**Comment by Jonlenes** [comment]
It worked. Awesome. Thanks
