### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by felixriese** [dovahcrow/patchify.py#8]
Are there plans to support Python 3.9?

I am not able to install `patchify` with Python 3.9. One problem seems to be a too old `scikit-image` version which is required by patchify. How can I help you on that?

**Comment by dovahcrow** [comment]
@felixriese Hi can you have a try on `pip install patchify -U`? I just updated the support for python 3.9

**Comment by felixriese** [comment]
Amazing, it works. Thanks!
