### ISSUE TITLE
Does unpatchify perform averaging ?

### ISSUE THREAD

**Issue by omagdy** [dovahcrow/patchify.py#9]
So I am doing some image processing on 3D images and rather than operate on the entire image I want to split it first into patches and perform the image processing on each patch. 

Say I have an image with dimensions 240x240x160 and I patchify it with a patch shape 40x40x40 and **20 as step size** then the patches will be overlapping.

My question is the following:
When these overlapping patches are unpatchified, **are the overlapping pixels averaged over all their values to get the final output ?**

Thanks in advance.

**Comment by dovahcrow** [comment]
No, there's no averaging for overlapping edges of the patches. The overlapped edges will be cropped away.

**Comment by yongshuo-Z** [comment]
Any plan to add the function for averaging for overlapping edges of the patches? Thanks!

**Comment by dovahcrow** [comment]
@yongshuo-Z https://github.com/dovahcrow/patchify.py/issues/6 I was planning to let this library support recovering from overlapped edges but haven't got time to implement it.
